let burguerJson = [
{ id: 1 , name: 'Hamburguer de Calabresa' , image: 'images/burguer1.jpg', description: 'Delicioso hamburguer de calabresa moida com cebola fatiada', 
price: 12.35} ,
{ id: 2 , name: 'Hamburguer de Quatro Queijos' , image: 'images/burguer2.jpg', description: 'Delicioso hamburguer de 4 queijos da marca Sadia', 
price: 11.37} ,
{ id: 3 , name: 'Hamburguer de Frango Catupiry' , image: 'images/burguer3.jpg', description: 'Delicioso hamburguer de frango desfiado com catupiry original', 
price: 17.48} ,
{ id: 4 , name: 'Hamburguer de Lombo' , image: 'images/burguer4.jpg', description: 'Delicioso hamburguer de fatias de lombo canadense defumado', 
price: 15.20} ,
{ id: 5 , name: 'Hamburguer de Costela' , image: 'images/burguer5.jpg', description: 'Delicioso hamburguer de costela feita no fogo 12 horas no bafo', 
price: 10.79} ,
{ id: 6 , name: 'Hamburguer de Suino' , image: 'images/burguer6.jpg', description: 'Delicioso hamburguer de costelinha de porco caipira mineiro na maça', 
price: 12.41} ,
{ id: 7 , name: 'Hamburguer Vegano' , image: 'images/burguer7.jpg', description: 'Delicioso hamburguer vegano, vegetariano, nelore puro e sem lactose', 
price: 27.80} ,
{ id: 8 , name: 'Hamburguer X-Tudo' , image: 'images/burguer8.jpg', description: 'Delicioso hamburguer reunindo tudo e todos os sabdores de lanches', 
price: 12.99} ,
{ id: 9 , name: 'Hamburguer X-Bacon-Egg' , image: 'images/burguer9.jpg', description: 'Delicioso hamburguer de bacon com ovo furado e frito a milanesa', 
price: 8.34} ,
{ id: 10 , name: 'Hamburguer X-Quaresma' , image: 'images/burguer10.jpg', description: 'Delicioso hamburguer para comer na quaresma que não contém carne', 
price: 15.14} ,
{ id: 11 , name: 'Hamburguer de Peixe' , image: 'images/burguer11.jpg', description: 'Delicioso hamburguer de carne branca de peixe porquinha do rio amazonas', 
price: 16.45} ,
{ id: 12 , name: 'Hamburguer de Picanha' , image: 'images/burguer12.jpg', description: 'Delicioso hamburguer de carne original de picanha de bovino padrao ouro.', 
price: 19.56} ,
];